// PWA 更新真实浏览器回归：node tests/pwa-update.cjs
// 使用本机 Edge + CDP，无新增依赖；PWA_ARTIFACT_DIR 可保留截图和结果。
const fs=require('fs'),path=require('path'),http=require('http'),cp=require('child_process'),assert=require('assert');
const root=path.resolve(__dirname,'..'),scratch=fs.mkdtempSync(path.join(require('os').tmpdir(),'jizhang-pwa-update-'));
const artifacts=process.env.PWA_ARTIFACT_DIR||scratch,results=[],errors=[],sleep=ms=>new Promise(r=>setTimeout(r,ms));
fs.mkdirSync(artifacts,{recursive:true});let browser,server;
class CDP{
 constructor(ws){this.ws=ws;this.id=0;this.pending=new Map();this.events=[];ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=this.pending.get(m.id);if(!p)return;this.pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);}else{this.events.push(m);if(m.method==='Runtime.exceptionThrown')errors.push(m);}};}
 static async connect(url){const ws=new WebSocket(url);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j});return new CDP(ws);}
 send(method,params={}){return new Promise((resolve,reject)=>{const id=++this.id,timer=setTimeout(()=>{this.pending.delete(id);reject(Error('CDP timeout '+method))},15000);this.pending.set(id,{resolve:v=>{clearTimeout(timer);resolve(v)},reject:e=>{clearTimeout(timer);reject(e)}});this.ws.send(JSON.stringify({id,method,params}));});}
 async eval(expression){const r=await this.send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;}
}
async function main(){
 const network={version:5,fail:false};
 server=http.createServer((req,res)=>{const name=new URL(req.url,'http://localhost').pathname,file=path.join(root,name==='/'?'index.html':name);if(!file.startsWith(root)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);return res.end()}
 if(network.fail==='offline'){req.socket.destroy();return}if(network.fail&&name!=='/sw.js'){res.writeHead(503);return res.end('core unavailable')}
 let content=fs.readFileSync(file);if(file.endsWith('sw.js'))content=Buffer.from(content.toString().replace("CACHE_PREFIX + 'v5'","CACHE_PREFIX + 'v"+network.version+"'"));
 if(file.endsWith('index.html'))content=Buffer.from(content.toString().replace('>v1.1.0<','>v1.1.'+(network.version-5)+'<'));
 res.setHeader('Content-Type',file.endsWith('.html')?'text/html;charset=utf-8':file.endsWith('.js')?'application/javascript':file.endsWith('.json')?'application/json':'image/png');res.setHeader('Cache-Control','no-store');res.end(content);});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
 browser=cp.spawn(process.env.EDGE_PATH||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',['--headless=new','--disable-gpu','--disable-extensions','--disable-sync','--no-first-run','--no-default-browser-check','--remote-debugging-port=0','--user-data-dir='+path.join(scratch,'profile'),'about:blank'],{windowsHide:true,stdio:'ignore'});
 let port;for(let i=0;i<100;i++){try{port=Number(fs.readFileSync(path.join(scratch,'profile/DevToolsActivePort'),'utf8').split('\n')[0]);break}catch{}await sleep(100)}assert(port,'Edge startup');
 const t=await(await fetch('http://127.0.0.1:'+port+'/json/new?about:blank',{method:'PUT'})).json(),a=await CDP.connect(t.webSocketDebuggerUrl);
 await a.send('Runtime.enable');await a.send('Page.enable');
 await a.send('Page.addScriptToEvaluateOnNewDocument',{source:`window.confirm=()=>true;sessionStorage.pwaLoads=Number(sessionStorage.pwaLoads||0)+1;
 const nativePost=ServiceWorker.prototype.postMessage;ServiceWorker.prototype.postMessage=function(message,...args){if(message?.type==='SKIP_WAITING')sessionStorage.pwaMessages=Number(sessionStorage.pwaMessages||0)+1;return nativePost.call(this,message,...args)};
 navigator.serviceWorker.addEventListener('controllerchange',()=>{sessionStorage.pwaChanges=Number(sessionStorage.pwaChanges||0)+1;if(window.duplicateChange&&!window.duplicated){window.duplicated=true;navigator.serviceWorker.dispatchEvent(new Event('controllerchange'))}});`});
 async function wait(expression){const deadline=Date.now()+10000;while(Date.now()<deadline){if(await a.eval(expression))return;await sleep(80)}throw Error('等待状态超时 '+expression)}
 async function navigate(){await a.send('Page.navigate',{url:origin});await wait("typeof pwaRegistration!=='undefined'&&pwaRegistration!==null");}
 async function reload(){await a.send('Page.reload');await wait("typeof pwaRegistration!=='undefined'&&pwaRegistration!==null");}
 async function click(selector){await sleep(300);const p=await a.eval(`(()=>{const e=document.querySelector(${JSON.stringify(selector)}),r=e.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2}})()`);await a.send('Input.dispatchMouseEvent',{type:'mousePressed',...p,button:'left',clickCount:1});await a.send('Input.dispatchMouseEvent',{type:'mouseReleased',...p,button:'left',clickCount:1});}
 async function record(name,fn){try{results.push({name,result:await fn()})}catch(e){results.push({name,error:String(e)})}console.log(JSON.stringify(results.at(-1)));fs.writeFileSync(path.join(artifacts,'results.json'),JSON.stringify(results,null,2));}
 await record('A-first-install-no-prompt',async()=>{await navigate();await wait('!!navigator.serviceWorker.controller');assert(await a.eval("document.getElementById('update-banner').hidden"));assert.equal(await a.eval('Number(sessionStorage.pwaLoads)'),1);assert.equal(await a.eval("document.querySelector('.dropdown-version').textContent"),'v1.1.0');return{firstClaimNoReload:true,noPrompt:true};});
 await record('normal-refresh-no-waiting',async()=>{await reload();assert(await a.eval("!pwaRegistration.waiting&&document.getElementById('update-banner').hidden"));return{noPrompt:true};});
 await record('B-new-worker-waits-current-page-usable',async()=>{await a.eval("caches.open('another-app-test');caches.open('ordinary-cache');window.oldController=navigator.serviceWorker.controller");network.version=6;await a.eval('pwaRegistration.update()');await wait("!!pwaRegistration.waiting&&!document.getElementById('update-banner').hidden");assert(await a.eval('navigator.serviceWorker.controller===oldController'));assert.equal(await a.eval("document.querySelector('.dropdown-version').textContent"),'v1.1.0');await a.eval("openAddModal();document.getElementById('input-raw-order').value='A ITEM 2 35';parseAndReview();confirmAddOrder()");assert.equal(await a.eval('orders.length'),1);return{waiting:true,oldPageUsable:true};});
 await record('F-mobile-and-desktop-layout-print-hidden',async()=>{for(const width of [390,1100]){await a.send('Emulation.setDeviceMetricsOverride',{width,height:844,deviceScaleFactor:1,mobile:width===390});const r=await a.eval(`(()=>{const box=e=>{const r=e.getBoundingClientRect();return{left:r.left,right:r.right,top:r.top,bottom:r.bottom}},banner=document.getElementById('update-banner');return{banner:box(banner),buttons:[...banner.querySelectorAll('button')].map(box),main:box(document.querySelector('.bottom-bar'))}})()`);assert(r.banner.left>=0&&r.banner.right<=width);assert(r.banner.bottom<r.main.top);assert(r.buttons.every(b=>b.left>=r.banner.left&&b.right<=r.banner.right&&b.top>=r.banner.top&&b.bottom<=r.banner.bottom));fs.writeFileSync(path.join(artifacts,'update-'+width+'.png'),Buffer.from((await a.send('Page.captureScreenshot')).data,'base64'));}await a.send('Emulation.setEmulatedMedia',{media:'print'});assert.equal(await a.eval("getComputedStyle(document.getElementById('update-banner')).display"),'none');await a.send('Emulation.setEmulatedMedia',{media:''});await a.send('Emulation.clearDeviceMetricsOverride');return{mobile:true,desktop:true,printHidden:true};});
 await record('later-dismiss-no-repeat',async()=>{await click('#update-banner .btn-ghost');assert(await a.eval("document.getElementById('update-banner').hidden"));await a.eval('showPwaUpdate(pwaRegistration)');assert(await a.eval("document.getElementById('update-banner').hidden"));return{dismissed:true};});
 await record('existing-waiting-detected-on-open',async()=>{await reload();await wait("!!pwaRegistration.waiting&&!document.getElementById('update-banner').hidden");return{waitingDetected:true};});
 await record('C-click-message-controllerchange-reload-once',async()=>{const before=await a.eval('Number(sessionStorage.pwaLoads)'),messages=await a.eval('Number(sessionStorage.pwaMessages||0)');await a.eval('window.duplicateChange=true');await click('#btn-update-now');await wait("document.querySelector('.dropdown-version').textContent==='v1.1.1'");await sleep(1000);assert.equal(await a.eval('Number(sessionStorage.pwaLoads)'),before+1);assert.equal(await a.eval('Number(sessionStorage.pwaMessages)'),messages+1);assert.equal(await a.eval('orders.length'),1);assert(await a.eval("!pwaRegistration.waiting&&document.getElementById('update-banner').hidden"));return{messageReceivedAndActivated:true,reloads:1,duplicateEventGuard:true,ledgerPreserved:true};});
 await record('E-only-own-old-caches-deleted',async()=>{const keys=await a.eval('caches.keys()');assert(!keys.includes('shuangbiao-v5'));for(const key of ['shuangbiao-v6','another-app-test','ordinary-cache'])assert(keys.includes(key));return{keys};});
 await record('D-failed-core-install-old-cache-offline',async()=>{network.version=7;network.fail=true;const result=await a.eval(`(async()=>{const reg=pwaRegistration,old=reg.active;const done=new Promise(resolve=>reg.addEventListener('updatefound',()=>{const w=reg.installing;w.addEventListener('statechange',()=>{if(w.state==='redundant')resolve(w.state)})},{once:true}));await reg.update();const state=await Promise.race([done,new Promise(resolve=>setTimeout(()=>resolve('timeout'),7000))]);return{state,sameWorker:reg.active===old,waiting:!!reg.waiting,hidden:document.getElementById('update-banner').hidden,keys:await caches.keys()}})()`);assert.equal(result.state,'redundant');assert(result.sameWorker&&!result.waiting&&result.hidden);assert(result.keys.includes('shuangbiao-v6'));network.fail='offline';await reload();assert.equal(await a.eval("document.querySelector('.dropdown-version').textContent"),'v1.1.1');assert.equal(await a.eval('orders.length'),1);network.fail=false;return{...result,oldOfflineLoaded:true};});
 await record('later-new-update-can-prompt-again',async()=>{await a.eval('pwaRegistration.update()');await wait("!!pwaRegistration.waiting&&!document.getElementById('update-banner').hidden");await click('#update-banner .btn-ghost');assert(await a.eval("document.getElementById('update-banner').hidden"));network.version=8;await a.eval('pwaRegistration.update()');await wait("!!pwaRegistration.waiting&&!document.getElementById('update-banner').hidden");return{newEventShows:true,samePageNewWorkerAfterDismiss:true};});
 await record('recovery-snapshot-not-lost-by-update',async()=>{const before=await a.eval('Number(sessionStorage.pwaLoads)');await a.eval("showDataProtection('test recovery',captureDataState())");await click('#btn-update-now');assert.equal(await a.eval('Number(sessionStorage.pwaLoads)'),before);assert(await a.eval('!!pwaRegistration.waiting&&!!dataProtection.snapshot'));return{reloadBlockedWhileRecovery:true};});
 await record('no-page-exceptions',async()=>{assert.equal(errors.length,0,JSON.stringify(errors));return{count:0};});
 const failed=results.filter(x=>x.error).length;console.log(JSON.stringify({summary:{total:results.length,failed}}));if(failed)process.exitCode=1;
 await a.send('Browser.close').catch(()=>{});a.ws.close();server.close();await sleep(500);if(!failed)fs.rmSync(scratch,{recursive:true,force:true,maxRetries:10,retryDelay:200});else console.error('测试证据：'+scratch);
}
main().catch(e=>{console.error(e);if(browser)browser.kill();if(server)server.close();process.exitCode=1});
